---
name: Glances
version: dev
slug: glances
description: A cross-platform system monitoring tool
url: https://github.com/hassio-addons/addon-glances
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:speedometer
startup: services
homeassistant: 0.92.0b2
arch:
  - aarch64
  - amd64
  - armv7
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
map:
  - addons
  - backup
  - config:rw
  - share
  - ssl
  - media
hassio_api: true
auth_api: true
docker_api: true
host_network: true
host_pid: true
apparmor: false
options:
  log_level: info
  process_info: false
  refresh_time: 10
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  influxdb:
    enabled: false
    host: a0d7b954-influxdb
    port: 8086
    interval: 60
    ssl: false
    version: 1
    username: glances
    password: ""
    database: glances
    prefix: localhost
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  process_info: bool
  refresh_time: int
  ssl: bool
  certfile: str
  keyfile: str
  influxdb:
    bucket: str?
    enabled: bool
    host: str
    port: port
    username: str?
    password: password?
    database: str?
    org: str?
    prefix: str?
    interval: int
    ssl: bool?
    token: str?
    version: int
  leave_front_door_open: bool?
environment:
  LOG_FORMAT: "{LEVEL}: {MESSAGE}"
